// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package srvctx

import (
	"context"
	"log/slog"
	"reflect"
	"time"
)

type ClientID string
type contextKey string

func keyFor[T any]() string {

	return cachedKey(reflect.TypeOf((*T)(nil)).Elem())
}

func WithCtx[T any](ctx context.Context, value T) context.Context {

	return context.WithValue(ctx, contextKey(keyFor[T]()), value)
}

func FromCtx[T any](ctx context.Context, defaults ...T) (value T) {

	var ok bool
	if value, ok = ctx.Value(contextKey(keyFor[T]())).(T); !ok {
		if len(defaults) != 0 {
			value = defaults[0]
		}
	}
	return
}

func GetLogger(ctx context.Context) *slog.Logger {

	return FromCtx[*slog.Logger](ctx)
}

func WithTimeout(parent context.Context, timeout time.Duration) (context.Context, context.CancelFunc) {
	return context.WithTimeout(parent, timeout)
}

func WithCancel(parent context.Context) (context.Context, context.CancelFunc) {
	return context.WithCancel(parent)
}

func GetClientID(ctx context.Context) string {

	if id := FromCtx[ClientID](ctx); id != "" {
		return string(id)
	}
	return "unknown"
}
