// Copyright (c) 2026 Khramtsov Aleksei (seniorGolang@gmail.com).
// conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

const DoNotEdit = "GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

const (
	TagTrace                  = "trace"
	TagMetrics                = "metrics"
	TagLogger                 = "log"
	TagLogSkip                = "log-skip"
	TagServerJsonRPC          = "jsonRPC-server"
	TagServerHTTP             = "http-server"
	TagHttpPrefix             = "http-prefix"
	TagHttpPath               = "http-path"
	TagHttpSuccess            = "http-success"
	TagHttpResponse           = "http-response"
	TagHttpEnableInlineSingle = "enableInlineSingle"
	TagHandler                = "handler"
	TagPackageJSON            = "packageJSON"
	TagHttpArg                = "http-args"
	TagHttpHeader             = "http-headers"
	TagHttpCookies            = "http-cookies"
	TagMethodHTTP             = "http-method"
	TagOmitemptyAll           = "tagOmitemptyAll"
	TagRequestContentType     = "requestContentType"
	TagResponseContentType    = "responseContentType"
	TagHttpMultipart          = "http-multipart"
	TagHttpPartName           = "http-part-name"
	TagHttpPartContent        = "http-part-content"
)

const (
	TypeIDIOReader     = "io:Reader"
	TypeIDIOReadCloser = "io:ReadCloser"
)

const (
	PackageFmt            = "fmt"
	PackageTime           = "time"
	PackageContext        = "context"
	PackageStrconv        = "strconv"
	PackageFiber          = "github.com/gofiber/fiber/v2"
	PackageFiberAdaptor   = "github.com/gofiber/adaptor/v2"
	PackageSlog           = "log/slog"
	PackageTrace          = "go.opentelemetry.io/otel/trace"
	PackageOTEL           = "go.opentelemetry.io/otel"
	PackagePrometheus     = "github.com/prometheus/client_golang/prometheus"
	PackagePrometheusAuto = "github.com/prometheus/client_golang/prometheus/promauto"
	PackagePrometheusHttp = "github.com/prometheus/client_golang/prometheus/promhttp"
	PackageAttributeOTEL  = "go.opentelemetry.io/otel/attribute"
	PackageTraceSDK       = "go.opentelemetry.io/otel/sdk/trace"
	PackageErrors         = "github.com/pkg/errors"
	PackageStrings        = "strings"
	PackageBytes          = "bytes"
	PackageSync           = "sync"
	PackageUUID           = "github.com/google/uuid"
	PackageStdJSON        = "encoding/json"
	PackageCors           = "github.com/lab259/cors"
	PackageReflect        = "reflect"
	PackageZeroLog        = "github.com/rs/zerolog"
	PackageMime           = "mime"
	PackageMimeMultipart  = "mime/multipart"
	PackageNetTextproto   = "net/textproto"
)

const (
	VarNameCtx  = "ctx"
	VarNameNext = "next"
	VarNameFtx  = "ftx"
)
