// Copyright (c) 2026 Khramtsov Aleksei (seniorGolang@gmail.com).
// conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

const DoNotEdit = "GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

const (
	TagTrace          = "trace"
	TagMetrics        = "metrics"
	TagLogger         = "log"
	TagLogSkip        = "log-skip"
	TagHttpResponse   = "http-response"
	TagHandler        = "handler"
	TagPackageJSON    = "packageJSON"
	TagOmitemptyAll   = "tagOmitemptyAll"
)

const (
	TypeIDIOReader     = "io:Reader"
	TypeIDIOReadCloser = "io:ReadCloser"
)

const (
	PackageFmt                  = "fmt"
	PackageTime                 = "time"
	PackageContext              = "context"
	PackageStrconv              = "strconv"
	PackageFiber                = "github.com/gofiber/fiber/v2"
	PackageFiberAdaptor         = "github.com/gofiber/adaptor/v2"
	PackageSlog                 = "log/slog"
	PackageTrace                = "go.opentelemetry.io/otel/trace"
	PackageOTEL                 = "go.opentelemetry.io/otel"
	PackagePrometheus           = "github.com/prometheus/client_golang/prometheus"
	PackagePrometheusAuto       = "github.com/prometheus/client_golang/prometheus/promauto"
	PackagePrometheusHttp       = "github.com/prometheus/client_golang/prometheus/promhttp"
	PackagePrometheusCollectors = "github.com/prometheus/client_golang/prometheus/collectors"
	PackageAttributeOTEL        = "go.opentelemetry.io/otel/attribute"
	PackageTraceSDK             = "go.opentelemetry.io/otel/sdk/trace"
	PackageErrors               = "github.com/pkg/errors"
	PackageStrings              = "strings"
	PackageBytes                = "bytes"
	PackageSync                 = "sync"
	PackageUUID                 = "github.com/google/uuid"
	PackageStdJSON              = "encoding/json"
	PackageCors                 = "github.com/lab259/cors"
	PackageReflect              = "reflect"
	PackageZeroLog              = "github.com/rs/zerolog"
	PackageMime                 = "mime"
	PackageMimeMultipart        = "mime/multipart"
	PackageNetTextproto         = "net/textproto"
	PackageURL                  = "net/url"
	PackageXML                  = "encoding/xml"
	PackageMsgpack              = "github.com/vmihailenco/msgpack/v5"
	PackageCBOR                 = "github.com/fxamacker/cbor/v2"
	PackageYAML                 = "gopkg.in/yaml.v3"
)

const (
	VarNameCtx  = "ctx"
	VarNameNext = "next"
	VarNameFtx  = "ftx"
)
