// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package tracer

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/utils"
	"go.opentelemetry.io/contrib"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/propagation"
	semconv "go.opentelemetry.io/otel/semconv/v1.38.0"
	"go.opentelemetry.io/otel/trace"
)

const (
	tracerKey           = "tracer-tg"
	instrumentationName = "tg"

	MetricNameHttpServerDuration       = "http.server.duration"
	MetricNameHttpServerRequestSize    = "http.server.request.size"
	MetricNameHttpServerResponseSize   = "http.server.response.size"
	MetricNameHttpServerActiveRequests = "http.server.active_requests"

	UnitDimensionless = "1"
	UnitBytes         = "By"
	UnitMilliseconds  = "ms"
)

func Middleware(opts ...Option) fiber.Handler {

	cfg := config{
		collectClientIP: true,
	}
	for _, opt := range opts {
		opt.apply(&cfg)
	}
	if cfg.TracerProvider == nil {
		cfg.TracerProvider = otel.GetTracerProvider()
	}
	tracer := cfg.TracerProvider.Tracer(
		instrumentationName,
		trace.WithInstrumentationVersion(contrib.Version()),
	)
	if cfg.MeterProvider == nil {
		cfg.MeterProvider = otel.GetMeterProvider()
	}
	meter := cfg.MeterProvider.Meter(
		instrumentationName,
		metric.WithInstrumentationVersion(contrib.Version()),
	)
	httpServerDuration, err := meter.Float64Histogram(MetricNameHttpServerDuration, metric.WithUnit(UnitMilliseconds), metric.WithDescription("measures the duration inbound HTTP requests"))
	if err != nil {
		otel.Handle(err)
	}
	httpServerRequestSize, err := meter.Int64Histogram(MetricNameHttpServerRequestSize, metric.WithUnit(UnitBytes), metric.WithDescription("measures the size of HTTP request messages"))
	if err != nil {
		otel.Handle(err)
	}
	httpServerResponseSize, err := meter.Int64Histogram(MetricNameHttpServerResponseSize, metric.WithUnit(UnitBytes), metric.WithDescription("measures the size of HTTP response messages"))
	if err != nil {
		otel.Handle(err)
	}
	httpServerActiveRequests, err := meter.Int64UpDownCounter(MetricNameHttpServerActiveRequests, metric.WithUnit(UnitDimensionless), metric.WithDescription("measures the number of concurrent HTTP requests that are currently in-flight"))
	if err != nil {
		otel.Handle(err)
	}
	if cfg.Propagators == nil {
		cfg.Propagators = otel.GetTextMapPropagator()
	}
	if cfg.SpanNameFormatter == nil {
		cfg.SpanNameFormatter = defaultSpanNameFormatter
	}
	return func(ftx *fiber.Ctx) error {

		if cfg.Next != nil && cfg.Next(ftx) {
			return ftx.Next()
		}
		ftx.Locals(tracerKey, tracer)
		savedCtx, cancel := context.WithCancel(ftx.UserContext())
		start := time.Now()
		requestMetricsAttrs := httpServerMetricAttributesFromRequest(ftx, cfg)
		httpServerActiveRequests.Add(savedCtx, 1, metric.WithAttributes(requestMetricsAttrs...))
		responseMetricAttrs := make([]attribute.KeyValue, 0, len(requestMetricsAttrs))
		copy(responseMetricAttrs, requestMetricsAttrs)
		reqHeader := make(http.Header)
		for k, v := range ftx.Request().Header.All() {
			reqHeader.Add(string(k), string(v))
		}
		ctx := cfg.Propagators.Extract(savedCtx, propagation.HeaderCarrier(reqHeader))
		options := []trace.SpanStartOption{
			trace.WithAttributes(httpServerTraceAttributesFromRequest(ftx, cfg)...),
			trace.WithSpanKind(trace.SpanKindServer),
		}
		spanName := utils.CopyString(ftx.Path())
		ctx, span := tracer.Start(ctx, spanName, options...)
		defer span.End()
		ftx.SetUserContext(ctx)
		if err = ftx.Next(); err != nil {
			span.RecordError(err)
			_ = ftx.App().Config().ErrorHandler(ftx, err)
		}
		responseAttrs := []attribute.KeyValue{
			semconv.HTTPResponseStatusCode(ftx.Response().StatusCode()),
			semconv.HTTPRoute(ftx.Route().Path),
		}
		requestSize, _ := strconv.ParseInt(string(ftx.Request().Header.Peek("Content-Length")), 10, 64)
		var responseSize int64
		if ftx.GetRespHeader("Content-Type") != "text/event-stream" {
			responseSize, _ = strconv.ParseInt(string(ftx.Response().Header.Peek("Content-Length")), 10, 64)
		}
		defer func() {
			responseMetricAttrs = append(responseMetricAttrs, responseAttrs...)
			httpServerActiveRequests.Add(savedCtx, -1, metric.WithAttributes(requestMetricsAttrs...))
			httpServerDuration.Record(savedCtx, float64(time.Since(start).Microseconds())/1000, metric.WithAttributes(responseMetricAttrs...))
			httpServerRequestSize.Record(savedCtx, requestSize, metric.WithAttributes(responseMetricAttrs...))
			httpServerResponseSize.Record(savedCtx, responseSize, metric.WithAttributes(responseMetricAttrs...))

			ftx.SetUserContext(savedCtx)
			cancel()
		}()
		span.SetAttributes(responseAttrs...)
		span.SetName(cfg.SpanNameFormatter(ftx))
		spanStatus, spanMessage := spanStatusFromHTTPStatusCodeAndSpanKind(ftx.Response().StatusCode(), trace.SpanKindServer)
		span.SetStatus(spanStatus, spanMessage)
		tracingHeaders := make(propagation.HeaderCarrier)
		cfg.Propagators.Inject(ftx.UserContext(), tracingHeaders)
		for _, headerKey := range tracingHeaders.Keys() {
			ftx.Set(headerKey, tracingHeaders.Get(headerKey))
		}
		return nil
	}
}

func defaultSpanNameFormatter(ftx *fiber.Ctx) string {

	return ftx.Route().Path
}

func spanStatusFromHTTPStatusCodeAndSpanKind(code int, kind trace.SpanKind) (codes.Code, string) {

	spanCode, valid := validateHTTPStatusCode(code)
	if !valid {
		return spanCode, fmt.Sprintf("Invalid HTTP status code %d", code)
	}
	if kind == trace.SpanKindServer && code/100 == 4 {
		return codes.Unset, ""
	}
	return spanCode, ""
}

func validateHTTPStatusCode(code int) (codes.Code, bool) {

	category := code / 100
	if category < 1 || category > 5 {
		return codes.Error, false
	}
	if category < 4 {
		return codes.Unset, true
	}
	return codes.Error, true
}
