// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package tracer

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/utils"
	"go.opentelemetry.io/otel/attribute"
	semconv "go.opentelemetry.io/otel/semconv/v1.38.0"
)

func httpServerMetricAttributesFromRequest(c *fiber.Ctx, cfg config) []attribute.KeyValue {

	flavor := "1.0"
	if c.Request().Header.IsHTTP11() {
		flavor = "1.1"
	}
	attrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String(utils.CopyString(c.Method())),
		semconv.NetworkProtocolVersion(flavor),
		semconv.URLScheme(utils.CopyString(c.Protocol())),
		semconv.HostName(utils.CopyString(c.Hostname())),
	}
	if cfg.Port != nil {
		attrs = append(attrs, semconv.ServerPort(*cfg.Port))
	}
	if cfg.ServerName != nil {
		attrs = append(attrs, semconv.ServerAddress(*cfg.ServerName))
	}
	if cfg.CustomMetricAttributes != nil {
		attrs = append(attrs, cfg.CustomMetricAttributes(c)...)
	}
	return attrs
}

func httpServerTraceAttributesFromRequest(c *fiber.Ctx, cfg config) []attribute.KeyValue {

	attrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String(utils.CopyString(c.Method())),
		semconv.URLScheme(utils.CopyString(c.Protocol())),
		semconv.URLPath(utils.CopyString(c.Path())),
		semconv.URLFull(utils.CopyString(c.OriginalURL())),
		semconv.UserAgentOriginal(string(utils.CopyBytes(c.Request().Header.UserAgent()))),
		semconv.HostName(utils.CopyString(c.Hostname())),
	}
	if cfg.collectClientIP {
		clientIP := c.IP()
		if len(clientIP) > 0 {
			attrs = append(attrs, semconv.ClientAddress(utils.CopyString(clientIP)))
		}
	}
	return attrs
}
