//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

import (
	"log/slog"

	"tgp/core/i18n"
	"tgp/core/wasm"
)

// StopServerByID останавливает HTTP сервер по его ID.
func StopServerByID(serverID uint64) (err error) {

	// Вызываем хост-функцию для остановки сервера
	ret := hostStopServer(serverID)

	// Обрабатываем ошибку
	if err = wasm.HandleHostError(ret); err != nil {
		slog.Error(i18n.Msg("StopServerByID: failed to stop server"), slog.Uint64("serverID", serverID), slog.String("error", err.Error()))
		return
	}

	slog.Info(i18n.Msg("StopServerByID: server has been stopped"), slog.Uint64("serverID", serverID))
	return
}
