// Copyright (c) 2026 Khramtsov Aleksei (seniorGolang@gmail.com).
// conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

const DoNotEdit = "GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

const (
	PackageOS                 = "os"
	PackageIO                 = "io"
	PackageFmt                = "fmt"
	PackageTLS                = "crypto/tls"
	PackageTime               = "time"
	PackageHttp               = "net/http"
	PackageURL                = "net/url"
	PackagePath               = "path"
	PackageContext            = "context"
	PackageStrconv            = "strconv"
	PackageBytes              = "bytes"
	PackageStrings            = "strings"
	PackageStdJSON            = "encoding/json"
	PackageErrors             = "errors"
	PackageReflect            = "reflect"
	PackageSort               = "sort"
	PackageUUID               = "github.com/google/uuid"
	PackageFiber              = "github.com/gofiber/fiber/v2"
	PackageSlog               = "log/slog"
	PackagePrometheus         = "github.com/prometheus/client_golang/prometheus"
	PackagePrometheusAuto     = "github.com/prometheus/client_golang/prometheus/promauto"
	tagPackageJSON = "packageJSON"
	TagMetrics     = "metrics"
	tagSummary     = "summary"
	tagDesc        = "desc"
)

const (
	PackageMime          = "mime"
	PackageMimeMultipart = "mime/multipart"
	PackageNetTextproto  = "net/textproto"
	PackageSync          = "sync"
	PackageXML           = "encoding/xml"
	PackageMsgpack       = "github.com/vmihailenco/msgpack/v5"
	PackageCBOR          = "github.com/fxamacker/cbor/v2"
	PackageYAML          = "gopkg.in/yaml.v3"
)

const (
	TypeIDIOReader     = "io:Reader"
	TypeIDIOReadCloser = "io:ReadCloser"
)
