// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package viewer

import (
	"strconv"
	"strings"
)

type option func(in []byte) (out []byte)

func applyOptions(in []byte, opts ...option) (view []byte) {
	view = make([]byte, len(in))
	copy(view, in)
	for _, opt := range opts {
		if opt != nil {
			view = opt(view)
		}
	}
	return
}

func hide(formula string) option {
	return func(in []byte) (view []byte) {
		var f, t int64
		switch {
		case formula == "fh":
			t = int64(len(in) / 2)
		case formula == "lh":
			f = int64(len(in) / 2)
		case formula == "md":
			f = int64(len(in) / 3)
			t = int64(len(in) - len(in)/3)
		case strings.Contains(formula, ":"):
			params := strings.Split(formula, ":")
			if len(params) == 2 {
				f, _ = strconv.ParseInt(params[0], 10, 32)
				t, _ = strconv.ParseInt(params[1], 10, 32)
			}
		}
		if formula != "-" {
			view = make([]byte, len(in))
			copy(view, in)
			view = append(view[:f], []byte(strings.Repeat("*", len(in)-int(f)))...)
			if t != 0 {
				view = append(view[:t], in[t:]...)
			}
		}
		return
	}
}
