// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package viewer

import (
	"fmt"
)

func Sprintln(a ...any) (s string) {
	return fmt.Sprintln(convertArgs(a)...)
}

func Sprintf(format string, a ...any) (s string) {
	return fmt.Sprintf(format, convertArgs(a)...)
}

func Sprint(a ...any) (s string) {
	return fmt.Sprint(convertArgs(a)...)
}

func Printf(format string, a ...any) (n int, err error) {
	return fmt.Printf(format, convertArgs(a)...)
}

func convertArgs(args []any) (formatters []any) {
	formatters = make([]any, len(args))
	for index, arg := range args {
		formatters[index] = NewFormatter(arg)
	}
	return
}

func newFormatter(cs *ConfigState, v any) fmt.Formatter {
	fs := &formatState{value: v, cs: cs}
	fs.pointers = make(map[uintptr]int)
	return fs
}

func NewFormatter(v any) fmt.Formatter {
	return newFormatter(&Config, v)
}
