// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package viewer

import (
	"strings"
)

const (
	tagName = "dumper"
	tagHide = "hide"
)

func tagToOption(tag string) (opt option) {

	parsed := strings.Split(tag, ",")
	if len(parsed) == 2 && parsed[0] == tagHide {
		return hide(parsed[1])
	}
	return
}
