// Copyright (c) 2020 Khramtsov Aleksei (seniorGolang@gmail.com).
// This file is subject to the terms and conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

import (
	"path"

	"tgp/plugins/client-ts/tsg"
)

// RenderClientBatch генерирует файл batch.ts.
func (r *ClientRenderer) RenderClientBatch() error {

	outDir := r.outDir
	file := tsg.NewFile()
	file.Comment("// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.\n")

	// Импорты
	file.ImportType("./jsonrpc/utils/jsonrpc", "RequestRPC", "ResponseRPC")

	// Генерируем тип BatchRequest (аналогично Go клиенту)
	// retHandler опциональный, так как устанавливается только если передан callback
	stmt := tsg.NewStatement()
	stmt.Export().Type("BatchRequest")
	stmt.Op("=")
	stmt.Values(func(vg *tsg.Group) {
		// Используем union тип для опционального поля: RpcCallback | undefined
		retHandlerType := tsg.NewStatement()
		retHandlerType.Id("RpcCallback").Op("|").Id("undefined")
		vg.Add(tsg.NewStatement().ObjectField("retHandler", retHandlerType))
		vg.Add(tsg.NewStatement().ObjectField("rpcRequest", tsg.NewStatement().Id("RequestRPC")))
	})
	file.Add(stmt.Semicolon())
	file.Line()

	// Генерируем тип RpcCallback (экспортируемый, аналогично Go клиенту)
	stmt2 := tsg.NewStatement()
	stmt2.Export().Type("RpcCallback")
	stmt2.Op("=")
	fnType := tsg.NewStatement()
	fnType.Params(func(fg *tsg.Group) {
		fg.Add(tsg.NewStatement().Id("error").Colon().Id("Error").Op("|").Id("null"))
		fg.Add(tsg.NewStatement().Id("response").Colon().Id("ResponseRPC").Op("|").Id("null"))
	}).Op("=>").Id("void")
	stmt2.Add(fnType).Semicolon()
	file.Add(stmt2)
	file.Line()

	// Генерируем импорты
	file.GenerateImports()

	return file.Save(path.Join(outDir, "batch.ts"))
}
