// Copyright (c) 2026 Khramtsov Aleksei (seniorGolang@gmail.com).
// conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

const DoNotEdit = "GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

const (
	TagServerJsonRPC      = "jsonRPC-server"
	TagServerHTTP         = "http-server"
	tagSummary            = "summary"
	tagRequired           = "required"
	TagMethodHTTP         = "http-method"
	TagHttpArg            = "http-args"
	TagHttpPath           = "http-path"
	TagHttpPrefix         = "http-prefix"
	TagHttpSuccess        = "http-success"
	TagHttpMultipart      = "http-multipart"
	TagHttpPartName       = "http-part-name"
	TagHttpPartContent    = "http-part-content"
	TagHttpHeader         = "http-headers"
	TagHttpCookies        = "http-cookies"
	TagEnableInlineSingle = "enableInlineSingle"
	TypeIDIOReader        = "io:Reader"
	TypeIDIOReadCloser    = "io:ReadCloser"
)
