// Copyright (c) 2026 Khramtsov Aleksei (seniorGolang@gmail.com).
// conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

const DoNotEdit = "GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

const (
	tagSummary     = "summary"
	tagRequired    = "required"
	TypeIDIOReader = "io:Reader"
	TypeIDIOReadCloser = "io:ReadCloser"
)
