// Copyright (c) 2020 Khramtsov Aleksei (seniorGolang@gmail.com).
// This file is subject to the terms and conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

const DoNotEdit = "GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

const (
	TagServerJsonRPC = "jsonRPC-server"
	TagServerHTTP    = "http-server"
	tagSummary       = "summary"
	tagRequired      = "required"
	TagMethodHTTP    = "http-method"
	TagHttpPath      = "http-path"
	TagHttpSuccess   = "http-success"
)
