// Copyright (c) 2026 Khramtsov Aleksei (seniorGolang@gmail.com).
// conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

import (
	"path"

	"tgp/plugins/client-ts/tsg"
)

func (r *ClientRenderer) RenderClientError() error {

	outDir := r.outDir
	file := tsg.NewFile()
	file.Comment("// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.\n")

	stmt := tsg.NewStatement()
	stmt.Export().Interface("ErrorJsonRPC", func(grp *tsg.Group) {
		grp.Add(tsg.NewStatement().Id("code").Colon().Id("number").Semicolon())
		grp.Add(tsg.NewStatement().Id("message").Colon().Id("string").Semicolon())
		grp.Add(tsg.NewStatement().Id("data").Optional().Colon().Id("any").Semicolon())
		grp.Add(tsg.NewStatement().Id("name").Colon().Id("string").Semicolon())
		grp.Add(tsg.NewStatement().Id("stack").Optional().Colon().Id("string").Semicolon())
	})
	file.Add(stmt)
	file.Line()

	stmt2 := tsg.NewStatement()
	stmt2.Export().Interface("WithErrorCode", func(grp *tsg.Group) {
		grp.Add(tsg.NewStatement().Id("code").Call().Colon().Id("number").Semicolon())
	})
	file.Add(stmt2)
	file.Line()

	stmt3 := tsg.NewStatement()
	stmt3.Export().Const("internalError").Op("=").Lit(-32603).Semicolon()
	file.Add(stmt3)
	file.Line()

	stmt4 := tsg.NewStatement()
	stmt4.Export().Type("ErrorDecoder")
	stmt4.Op("=")
	fnType := tsg.NewStatement()
	fnType.Params(func(fg *tsg.Group) {
		fg.Add(tsg.NewStatement().Id("errData").Colon().Id("any"))
	}).Op("=>").Id("Error")
	stmt4.Add(fnType).Semicolon()
	file.Add(stmt4)
	file.Line()

	stmt5 := tsg.NewStatement()
	stmt5.Export().Func("defaultErrorDecoder")
	stmt5.Params(func(pg *tsg.Group) {
		pg.Add(tsg.NewStatement().Id("errData").Colon().Id("any"))
	})
	stmt5.Colon().Id("Error")
	stmt5.BlockFunc(func(bg *tsg.Group) {
		bg.Add(tsg.NewStatement().Const("jsonrpcError").Colon().Id("ErrorJsonRPC").Op("=").Id("errData").Op("as").Id("ErrorJsonRPC").Semicolon())
		bg.Return(tsg.NewStatement().Id("jsonrpcError"))
	})
	file.Add(stmt5)
	file.Line()

	file.GenerateImports()

	return file.Save(path.Join(outDir, "error.ts"))
}
