// Copyright (c) 2026 Khramtsov Aleksei (seniorGolang@gmail.com).
// conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

import (
	"fmt"
	"os"
	"path"

	"github.com/goccy/go-json"
)

func (r *ClientRenderer) RenderTsConfig() error {
	outDir := r.outDir

	// Структура для tsconfig.json
	tsConfig := map[string]any{
		"compilerOptions": map[string]any{
			"target":                           "ES2020",
			"module":                           "ES2020",
			"lib":                              []string{"ES2020", "DOM"},
			"moduleResolution":                 "bundler",
			"strict":                           true,
			"esModuleInterop":                  true,
			"skipLibCheck":                     true,
			"resolveJsonModule":                true,
			"allowSyntheticDefaultImports":     true,
			"forceConsistentCasingInFileNames": true,
			"declaration":                      true,
			"declarationMap":                   true,
			"sourceMap":                        true,
			"noUnusedLocals":                   true,
			"noUnusedParameters":               true,
		},
		"include": []string{
			"**/*.ts",
		},
		"exclude": []string{
			"node_modules",
		},
	}

	// Сериализуем в JSON с отступами
	jsonData, err := json.MarshalIndent(tsConfig, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal tsconfig.json: %w", err)
	}

	fileContent := "// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.\n" + string(jsonData) + "\n"

	// Сохраняем файл
	tsConfigPath := path.Join(outDir, "tsconfig.json")
	if err := os.WriteFile(tsConfigPath, []byte(fileContent), 0600); err != nil {
		return fmt.Errorf("failed to write tsconfig.json: %w", err)
	}

	return nil
}
