// Copyright (c) 2020 Khramtsov Aleksei (seniorGolang@gmail.com).
// This file is subject to the terms and conditions defined in file 'LICENSE', which is part of this project source code.
package renderer

import (
	"path"

	"tgp/plugins/client-ts/tsg"
)

// RenderVersion генерирует файл version.ts.
func (r *ClientRenderer) RenderVersion() error {

	outDir := r.outDir
	file := tsg.NewFile()
	file.Comment("// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.\n")

	stmt := tsg.NewStatement()
	stmt.Export().Const("VersionTg").Op("=").Lit(r.project.Version).Semicolon()
	file.Add(stmt)
	file.Line()

	// Генерируем импорты
	file.GenerateImports()

	return file.Save(path.Join(outDir, "version.ts"))
}
