// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package logger

import (
	"context"
	"io"
	"log/slog"

	"github.com/rs/zerolog"
)

type Handler struct {
	logger zerolog.Logger
	level  slog.Level
}

func New(w io.Writer) *Handler {
	logger := zerolog.New(w).With().Timestamp().Logger()
	return &Handler{
		logger: logger,
		level:  slog.LevelInfo,
	}
}

func NewWithLogger(logger zerolog.Logger) *Handler {
	return &Handler{
		logger: logger,
		level:  slogLevel(logger.GetLevel()),
	}
}

func (h *Handler) Enabled(ctx context.Context, level slog.Level) bool {
	return level >= h.level
}

func (h *Handler) Handle(ctx context.Context, record slog.Record) error {
	logEvent := func(event *zerolog.Event) {
		if event == nil {
			return
		}

		event.Time("time", record.Time)

		record.Attrs(func(a slog.Attr) bool {
			addAttr(event, a)
			return true
		})

		event.Msg(record.Message)
	}

	switch level := zerologLevel(record.Level); level {
	case zerolog.ErrorLevel:
		logEvent(h.logger.Error())
	case zerolog.WarnLevel:
		logEvent(h.logger.Warn())
	case zerolog.InfoLevel:
		logEvent(h.logger.Info())
	case zerolog.DebugLevel:
		logEvent(h.logger.Debug())
	default:
		logEvent(h.logger.Trace())
	}
	return nil
}

func (h *Handler) WithAttrs(attrs []slog.Attr) slog.Handler {
	ctx := h.logger.With()
	for _, attr := range attrs {
		ctx = addAttrToContext(ctx, attr)
	}
	return &Handler{
		logger: ctx.Logger(),
		level:  h.level,
	}
}

func (h *Handler) WithGroup(name string) slog.Handler {
	return &Handler{
		logger: h.logger.With().Str("group", name).Logger(),
		level:  h.level,
	}
}

func zerologLevel(level slog.Level) zerolog.Level {
	switch {
	case level >= slog.LevelError:
		return zerolog.ErrorLevel
	case level >= slog.LevelWarn:
		return zerolog.WarnLevel
	case level >= slog.LevelInfo:
		return zerolog.InfoLevel
	case level >= slog.LevelDebug:
		return zerolog.DebugLevel
	default:
		return zerolog.TraceLevel
	}
}

func slogLevel(level zerolog.Level) slog.Level {
	switch level {
	case zerolog.Disabled:
		return slog.Level(999) // Максимальный уровень, чтобы отключить логирование
	case zerolog.ErrorLevel, zerolog.FatalLevel, zerolog.PanicLevel:
		return slog.LevelError
	case zerolog.WarnLevel:
		return slog.LevelWarn
	case zerolog.InfoLevel:
		return slog.LevelInfo
	case zerolog.DebugLevel:
		return slog.LevelDebug
	case zerolog.TraceLevel:
		return slog.LevelDebug
	default:
		return slog.LevelInfo
	}
}

func addAttr(event *zerolog.Event, attr slog.Attr) *zerolog.Event {
	key := attr.Key
	value := attr.Value.Resolve()

	switch value.Kind() {
	case slog.KindString:
		return event.Str(key, value.String())
	case slog.KindInt64:
		return event.Int64(key, value.Int64())
	case slog.KindUint64:
		return event.Uint64(key, value.Uint64())
	case slog.KindFloat64:
		return event.Float64(key, value.Float64())
	case slog.KindBool:
		return event.Bool(key, value.Bool())
	case slog.KindDuration:
		return event.Dur(key, value.Duration())
	case slog.KindTime:
		return event.Time(key, value.Time())
	case slog.KindAny:
		return event.Interface(key, value.Any())
	default:
		return event.Interface(key, value.Any())
	}
}

func addAttrToContext(ctx zerolog.Context, attr slog.Attr) zerolog.Context {
	key := attr.Key
	value := attr.Value.Resolve()

	switch value.Kind() {
	case slog.KindString:
		return ctx.Str(key, value.String())
	case slog.KindInt64:
		return ctx.Int64(key, value.Int64())
	case slog.KindUint64:
		return ctx.Uint64(key, value.Uint64())
	case slog.KindFloat64:
		return ctx.Float64(key, value.Float64())
	case slog.KindBool:
		return ctx.Bool(key, value.Bool())
	case slog.KindDuration:
		return ctx.Dur(key, value.Duration())
	case slog.KindTime:
		return ctx.Time(key, value.Time())
	case slog.KindAny:
		return ctx.Interface(key, value.Any())
	default:
		return ctx.Interface(key, value.Any())
	}
}

func SetLevel(logger *slog.Logger, level slog.Level) {
	if handler, ok := logger.Handler().(*Handler); ok {
		handler.SetLevel(level)
	}
}

func (h *Handler) SetLevel(level slog.Level) {
	h.level = level
}

func (h *Handler) Logger() zerolog.Logger {
	return h.logger
}

func NewLogger(w io.Writer) *slog.Logger {
	return slog.New(New(w))
}

func NewZerolog(logger zerolog.Logger) *slog.Logger {
	return slog.New(NewWithLogger(logger))
}
